name: fusecash
version: 1.0.0+9
description: A new Flutter project.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  cupertino_icons: ^0.1.2
  flutter_secure_storage: ^3.1.2
  intl: ^0.15.7
  flutter_redux: ^0.5.4
  redux_thunk: ^0.2.1
  redux_logging: ^0.3.0
  redux_persist: ^0.8.2
  redux_persist_flutter: ^0.8.2
  country_code_picker: ^1.1.5
  wallet_core: ^0.0.1+34
  alphabet_list_scroll_view: ^1.0.5
  flutter_slidable: 0.5.4
  contacts_service: ^0.3.9
  permission_handler: ^4.0.0
  virtual_keyboard: ^0.1.4
  qr_flutter: ^3.1.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - 
      family: Europa
      fonts: 
        - 
          asset: assets/fonts/europa-regular-webfont.ttf
        - 
          asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - 
          asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - 
          asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - 
          asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - 
          asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - 
          asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
