name: digitalrand
version: 1.1.32+199
description: A new Flutter project.
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  enum_to_string: ^1.0.9
  local_auth: ^0.6.2+3
  auto_size_text: ^2.1.0
  flutter_webview_plugin: ^0.3.11
  phone_number: ^0.6.2+2
  libphonenumber: ^1.0.1
  cached_network_image: ^2.0.0
  rate_my_app: ^0.6.0+2
  auto_route: ^0.3.1
  url_launcher: ^5.4.2
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.25+3
  equatable: ^1.1.1
  shared_preferences: ^0.5.6+3
  package_info: ^0.4.0+16
  share: ^0.6.3+6
  flutter_svg: ^0.17.3+1
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.2
  flutter_redux: ^0.6.0
  flutter_dotenv: ^2.1.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  redux_persist: ^0.8.2
  country_code_picker: ^1.3.9
  wallet_core: ^0.2.3+16
  # wallet_core:
    # path: ../../wallet_core
  barcode_scan: ^2.0.1
  flutter_slidable: ^0.5.4
  contacts_service: ^0.3.10
  permission_handler: ^4.4.0+hotfix.2
  virtual_keyboard: ^0.1.4
  qr_flutter: ^3.2.0
  logger_flutter: ^0.7.1
  path_provider: ^1.6.5
  json_annotation: ^3.0.1
  pin_input_text_field: ^3.0.1
  flare_flutter: ^2.0.1
  decimal: ^0.3.5
  flutter_segment: ^2.0.2
  firebase_messaging: ^6.0.13
  firebase_auth: ^0.15.5+3
  ethereum_address: ^1.0.1
  sentry: ">=3.0.0 <4.0.0"
  device_info: ^0.4.2+1
  flutter_cupertino_localizations: ^1.0.1
  flutter_branch_sdk: ^0.3.1
  flutter_udid: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^0.3.2
  flutter_native_splash: ^0.1.9
  # dependency_validator: ^1.4.2
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: assets/images/icon_app.png
  android: true
  ios: true
flutter:
  assets:
    - .env
    - .env_qa
    - assets/
    - assets/images/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
