name: fusecash
version: 1.1.60+292
description: Cross platform mobile Ethereum wallet.
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  auto_size_text_field: ^0.1.7
  lottie: ^0.7.0+1
  numeric_keyboard: ^1.0.1
  pin_code_fields: ^6.1.0
  flex_color_scheme: ^1.4.1
  freezed_annotation: ^0.12.0
  pretty_dio_logger: ^1.1.1
  get_it: ^5.0.6
  injectable: ^1.1.2
  dio: ^3.0.10
  smooth_page_indicator: ^0.2.1
  font_awesome_flutter: ^8.10.0
  flushbar: ^1.10.4
  flutter_platform_widgets: ^0.71.0
  enum_to_string: ^1.0.14
  local_auth: ^0.6.3+4
  auto_size_text: ^2.1.0
  webview_flutter: ^1.0.7
  phone_number: ^0.8.1
  cached_network_image: ^2.5.0
  auto_route: ^0.6.9
  url_launcher: ^5.7.10
  google_maps_flutter: ^1.2.0
  equatable: ^1.2.6
  package_info: ^0.4.3+2
  share: ^0.6.5+4
  flutter_svg: ^0.19.1
  cupertino_icons: ^1.0.0
  flutter_secure_storage: ^3.3.5
  flutter_redux: ^0.7.0
  flutter_dotenv: ^3.1.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  redux_persist: ^0.8.4
  country_code_picker: ^1.7.0
  # wallet_core: ^0.2.4+21
  # wallet_core:
  #   path: ../wallet_core
  wallet_core:
    git:
      url: https://github.com/fuseio/wallet_core.git
      ref: next
  barcode_scan: ^3.0.1
  flutter_slidable: ^0.5.7
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  qr_flutter: ^3.2.0
  logger: ^0.9.4
  json_annotation: ^3.1.1
  flare_flutter: ^2.0.6
  decimal: ^0.3.5
  flutter_segment: 2.1.1
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  ethereum_address: ^1.0.1
  sentry_flutter: ^4.0.6
  device_info: ^1.0.0
  image_picker: ^0.6.7+22
  flutter_cupertino_localizations: ^1.0.1
  flutter_branch_sdk: 1.3.3
  flutter_udid: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  freezed: ^0.12.7
  lint: ^1.3.1
  injectable_generator: ^1.1.2
  auto_route_generator: ^0.6.10
  flutter_native_splash: ^0.3.0
  dependency_validator: ^2.0.1
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
