name: fusecash
version: 0.1.13+127
description: Cross platform mobile Ethereum wallet.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  wallet_connect_flutter:
    path: ../wallet-connect-flutter
  upgrader: ^3.3.1
  advertising_id: ^2.0.0
  slide_countdown_clock:
    path: ../slide_countdown_clock
  jiffy: ^4.1.0
  facebook_app_events: ^0.12.0
  intercom_flutter: ^5.0.0
  confetti: ^0.6.0-nullsafety
  flutter_localized_locales: ^2.0.2
  app_tracking_transparency: ^2.0.1
  rate_my_app: ^1.1.0+1
  responsive_framework: ^0.1.4
  flutter_web_browser: ^0.14.0
  modal_bottom_sheet: ^2.0.0
  grouped_list: ^4.0.0
  fl_chart: ^0.36.2
  number_display: ^3.0.0
  auto_size_text_field: ^1.0.0-nullsafety.1
  lottie: ^1.1.0
  pin_code_fields: ^7.2.0
  flex_color_scheme: ^3.0.1
  freezed_annotation: ^0.14.2
  # pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0
  injectable: ^1.4.1
  dio: ^4.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  font_awesome_flutter: ^9.1.0
  # flushbar: ^1.10.4
  # fluttertoast: ^8.0.7
  flushbar:
    git:
      url: git://github.com/prasadsunny1/flushbar
      ref: master
  flutter_platform_widgets: ^1.9.5
  enum_to_string: ^2.0.1
  local_auth: ^1.1.6
  auto_size_text: ^3.0.0-nullsafety.0
  webview_flutter: ^2.0.10
  phone_number: ^0.11.0+1
  cached_network_image: ^3.1.0
  auto_route: ^2.2.0
  url_launcher: ^6.0.9
  google_maps_flutter: ^2.0.6
  equatable: ^2.0.3
  package_info: ^2.0.2
  share: ^2.0.4
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^4.2.0
  flutter_redux: ^0.8.2
  flutter_dotenv: ^5.0.0
  redux_thunk: ^0.4.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  country_code_picker: ^2.0.2
  wallet_core:
    path: ../wallet_core
  # wallet_core:
  #   git:
  #     url: https://github.com/fuseio/wallet_core.git
  #     ref: feat/null-safety
  scan: ^1.4.3
  flutter_slidable: ^0.6.0
  contacts_service: ^0.6.1
  permission_handler: ^8.1.3
  qr_flutter: ^4.0.0
  logger: ^1.0.0
  json_annotation: ^4.0.1
  flare_flutter: ^3.0.1
  decimal: ^1.2.0
  firebase_remote_config: ^0.10.0+3
  firebase_messaging: ^10.0.4
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  ethereum_address:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  sentry_flutter: ^5.1.0
  image_picker: ^0.8.2
  # flutter_segment: ^3.1.0
  flutter_segment:
    git:
      url: https://github.com/fuseio/flutter-segment.git
      ref: master
  flutter_cupertino_localizations: ^1.0.1
  flutter_branch_sdk: ^3.3.0
  appsflyer_sdk: ^6.3.2-nullsafety.0
  flutter_udid: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  freezed: ^0.14.2
  lint: ^1.5.3
  injectable_generator: ^1.4.1
  auto_route_generator: ^2.1.0
  flutter_native_splash: ^1.1.8+4
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
  # generate: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
  localizely:
    project_id: 059fb9dd-4449-4e79-92ef-4d786cf38e5a
    download_empty_as: main
